### ISSUE TITLE
Inspirations cactus doesn't drop cactus

### ISSUE THREAD

**Issue by dlswimmer** [Gogo08190/chroma-sky#1]
I just updated to 1.0.1 and I see that we can now craft cactus seeds from inspirations. When using the seed on sand, I then grow it with bone meal, but when getting to the largest size and right clicking it seems like it is trying to drop one (like with the sugarcane seed), but nothing is dropped. It seems like it might be disappearing like it does with dropping items on a cactus.

**Comment by Gogo08190** [comment]
Hello, you can put the seed on some snad and grow it up to 3 high and then collect it
