### ISSUE TITLE
Drop FPS

### ISSUE THREAD

**Issue by franckcle** [Gogo08190/chroma-sky#2]
Bonjour,
J'ai télécharger le modpack hier, et je rencontre un problème de drop de FPS. A intervalle, à priori, régulier j'ai les FPS qui tombe à 0 quelques secondes. J'avoue ne pas comprendre vu que j'ai les même réglages pour ce modpack que pour PO3, Chroma Technologie et RL Craft pour lesquels je n'ai aucun problème. Sur tous les modpack, j'ai, au minimum, 8Go alloué. Auriez-vous une solution?

**Comment by Gogo08190** [comment]
Bonjour, je t'invite a tester la version 1.0.2 du modpack j'ai  travaillé sur l'optimisation du pack

**Comment by franckcle** [comment]
Bonjour,
J'ai mis à jour le pack, mais rien y fait. Ensuite j'ai tout désinstaller et réinstaller, pareil. J'ai fais une maj de java, pas plus de succès. J'ai fini par le monter à 10Go, toujours pareil. As-tu d'autres option ?

**Comment by Gogo08190** [comment]
Si tu es passé en 1.0.2 ça devrait être bon sinon le soucis vient de ton coté et je n'ai pas forcément de solutions.

**Comment by franckcle** [comment]
Ok Je vais continuer mes recherches de mon coté. Bonne continuation.
