### ISSUE TITLE
Lancement serveur 1.0.4

### ISSUE THREAD

**Issue by Reivax69008** [Gogo08190/chroma-sky#3]
Bonjour,

J'ai l'erreur suivante quand j'essai de lancer le serveur sur mon PC.
[18:34:48] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:items
[18:34:48] [Server thread/ERROR] [FML]:     tp:pouch: 12886

Auriez-vous une idée?
Je suis repasser en 1.0.2 car j'avais aussi un souci en 1.0.3 et là mes enfants me demandent d'installer la 1.0.4.
Si vous pouviez m'aider.

Merci

**Comment by Gogo08190** [comment]
Bonjour, 
Sur la version 1.0.4 a un moment dans la console tu vas devoir faire la commande /fml confirm
