### ISSUE TITLE
Prosperity sappling

### ISSUE THREAD

**Issue by Nereldus** [Gogo08190/chroma-sky#4]
Salut Gogo08,

Sur mon serveur, la menril sapling ne peut pas pousser lors du ritual of the forest. Probablement car l'arbre est plus gros que les autres, ou alors il y a un autre problème que je ne connais pas. Dans tous les cas je fais remonter l'info.

J'ai eu ce problème en 1.0.3 et je l'ai encore en 1.0.4.

Cordialement

**Comment by Gogo08190** [comment]
Le craft fonctionne très bien tu as du faire le rituel dans le mauvais sens. Il faut faire pousser l'arbre en dernier
