### ISSUE TITLE
Bug de duplication avec uncrafting grinder

### ISSUE THREAD

**Issue by Darcodo** [Gogo08190/chroma-sky#5]
![2021-03-08_13 58 02](https://user-images.githubusercontent.com/80262660/110324751-afae3e80-8016-11eb-8e12-7d5f69e0f3c5.png)
![2021-03-08_13 58 07](https://user-images.githubusercontent.com/80262660/110324755-b341c580-8016-11eb-8b83-1bbceec8e269.png)
![2021-03-08_13 58 18](https://user-images.githubusercontent.com/80262660/110324758-b63cb600-8016-11eb-9d35-e6575e3844ed.png)
![2021-03-08_13 58 24](https://user-images.githubusercontent.com/80262660/110324765-b9d03d00-8016-11eb-8f02-5fa1d7d3a2bc.png)
![2021-03-08_13 58 37](https://user-images.githubusercontent.com/80262660/110324776-bdfc5a80-8016-11eb-875a-f0a3bc57fd6e.png)
voici des images un bug de duplication que l'on peux faire en boucle

**Comment by RobertLSnead** [comment]
Why not just disable the uncrafting grinder?
I had the same issue but with other items, after disabling it stopped :P
