### ISSUE TITLE
Impossibilité de trouver de l'angolium et du veranium

### ISSUE THREAD

**Issue by Olivier83140** [Gogo08190/chroma-sky#8]
Bonjour,
Après avoir effectué des recherches intensives ces deux derniers jours je me tourne ici dans un dernier espoir.
En effet sous chroma sky, je souhaite faire la philosopher stone. Sauf que, je n'arrive pas à trouver ce con d'angolium et de veranium ore.
Je sais qu'on les trouve uniquement dans l'equivalent planet, mais je n'ai rien trouvé la bas malgré des heures de recherches appuyé d'un digital miner..
Ou puis-je enfin trouver ces minerais svp ?
Merci !
Même avec la quantum quarry j'en ai pas..
Version 1.0.6 du modpack

**Comment by Gogo08190** [comment]
Merci de passer en version 1.1.0 du modpack.
Tu peux en faire via le Void Ore T6.
